# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Variável para armazenar a soma
n = 0
# Variável para armazenar o primeiro e o segundo algarismo da sequência de Fibonacci
f1 = 0
f2 = 1
# Inicia um loop infinito
while True:
    # O terceiro termo é a soma dos primeiros dois termos da progressão

    f3 = f1 + f2 # f3 = 1 (0 + 1)

    # O primeiro termo assume o valor do segundo e o segundo assume o valor do terceiro,
    # o que faz a progressão andar sem a necessidade de criar variáveis extras.

    f1 = f2 # f1 = 1
    f2 = f3 # f2 = 1, o próximo f3 será 2, já que f3 = 1 + 1, e assim por diante.

    # Checa se f3 é par e adiciona à soma total, caso seja
    if f3 % 2 == 0:
        n += f3

    # Cria a condição de parada, caso f3 ultrapasse quatro milhões
    if f3 > 4_000_000:
        break

print(n)
